### ISSUE TITLE
A2: Somesort of forecasting

### ISSUE THREAD

**Issue by nbel806** [nathanbell806/310A1BudgetTracker#54]
**What feature are you asking for**
What would happen if a user saved this much money for a whole year

**Describe the solution you'd like**
An extra page showing how much a user would have spent or saved in a category over a longer time frame

**Reason**
Give people a goal, eg if we save 500 per month we'll save x over y time. Then we can buy a house

**Comment by tmur647** [comment]
Yep, this seems like a reasonable idea
