### ISSUE TITLE
Category screen scalling issue

### ISSUE THREAD

**Issue by Yxin-KaiByz** [nathanbell806/310A1BudgetTracker#64]
**Describe the bug**
The scale of the category view is inconsistent with other views

**To Reproduce**
Entering the category view after setting any budget value
**Expected behavior**
The category view should have the same scaling and resolution as other views

**Observed result**
The category view is currently too small and includes huge empty spaces

**Screenshots**
![image](https://github.com/nathanbell806/310A1BudgetTracker/assets/100540976/8d30c6ff-077c-487e-bc47-ce401393bbef)

**Comment by yxin202** [comment]
Approved
