### ISSUE TITLE
Get user input from budget entry.

### ISSUE THREAD

**Issue by yxin202** [nathanbell806/310A1BudgetTracker#70]
**What feature are you asking for**
Get data from the user from budget entry and apply it to the budget category scene.

**Describe the solution you'd like**
Get information from currently signed in profile.

**Reason**
It makes more sense to show the user the budget value they set.

**Comment by nbel806** [comment]
Think this may be a duplicate

**Comment by yxin202** [comment]
It is quite different since I need to gather information to correctly show the budget value in the budget category sence

**Comment by nbel806** [comment]
approved,
CurrentProfile.getInstance().getCurrentProfile().getBudget(); will return you the total budget anywhere in the app. Think this might be helpful, cause I used for total budget value in the piechart
